import './globals.scss';
import type { Metadata } from 'next';
import { Titillium_Web } from 'next/font/google';

const titillium = Titillium_Web({ weight: '400', subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Главная | Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={titillium.className}>{children}</body>
    </html>
  );
}
